[project]
name = "agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "groq>=1.7.0",
    "numpy>=2.4.6",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.0",
    "sentence-transformers>=6.0.1",
    "tavily-python>=0.8.1",
]
